
#use spaces not tab !
{ 
  'ARK':{
    'urls':['http://localhost:8000/1hour.log','http://localhost:8000/monitor-perf.ark.full.log'],
    'focus_on_service':['*','Portefeuille']
  },
  'FTN':{
    'urls':['http://localhost:8000/1hour.log','http://localhost:8000/monitor-perf.ark.full.log'],
    'focus_on_service':['*','PassageOrdre']
  } 
}