
#use spaces not tab !
{ 
'targets':{
    'FTN':{
       'urls':['http://spcontrol-1-a.gicm.net:8443/spcontrol-ftn/monitor-perf.log','http://spcontrol-1-b.gicm.net:8443/spcontrol-ftn/monitor-perf.log'],
       'focus_on_service':['.*','PassageOrdre','Portefeuille','CarnetOrdre','SyntheseCompte','SaisieOrdre'],
       'png_dir':'/opt/monitorperf/images/FTN/',
       'report_dir':'/opt/monitorperf/reports/FTN',
       'monitorperflogversion':1
    },
    'ARK':{
       'urls':['http://spcontrol-1-a.gicm.net:8443/spcontrol-ark/monitor-perf.log','http://spcontrol-1-b.gicm.net:8443/spcontrol-ark/monitor-perf.log'],
       'focus_on_service':['.*','PassageOrdre','Portefeuille','CarnetOrdre','SyntheseCompte','SaisieOrdre'],
       'png_dir':'/opt/monitorperf/images/ARK/',
       'report_dir':'/opt/monitorperf/reports/ARK',
       'monitorperflogversion':1
    },
    'EAB':{
       'urls':['http://spcontrol-1-a.gicm.net:8443/spcontrol-eab/monitor-perf.log','http://spcontrol-1-b.gicm.net:8443/spcontrol-eab/monitor-perf.log'],
       'focus_on_service':['.*','PassageOrdre','Portefeuille','CarnetOrdre','SyntheseCompte'],
       'png_dir':'/opt/monitorperf/images/EAB/',
       'report_dir':'/opt/monitorperf/reports/EAB',
       'monitorperflogversion':1
    }        
},
'global':{
   #Sur l'axe du temps écrire un label toutes les X mesures
   'XLABELFREQUENCY':900,
   #Remplacer les temps de reponse > GLOBALCUTOFF par GLOBALCUTOFF
   # (pas pris en compte pour le calcul des moyennes mouvantes)   
   'GLOBALCUTOFF':500,
    #Remplacer les temps de reponse Recif carac > RECIFCUTOFF par RECIFCUTOFF
    # (pas pris en compte pour le calcul des moyennes mouvantes)   
   'RECIFCUTOFF':80,
   'RECIFTRCUTOFF':100,
   'HOSTCUTOFF':250,
   'INTERNALCUTOFF':350,
   'PACMANCUTOFF':150,
   #nb de valeurs prises en comptre pour le calcul de la moyenne flottante
   'WINDOWSSIZE':1000,
   'XTICKNUMBER':30

}  
}