
#use spaces not tab !
{ 
'targets':{
    'ARK':{
       'urls':['http://localhost:8000/1hour.log','http://localhost:8000/1hour.log'],
       'focus_on_service':['.*','Portefeuille'],
       'png_dir':'/opt/monitorperf/images/ARK/',
       'report_dir':'/opt/monitorperf/reports/ARK'
    },
    'FTN':{
       'urls':['http://localhost:8000/1hour.log','http://localhost:8000/1hour.log'],
       'focus_on_service':['.*','PassageOrdre'],
       'png_dir':'/opt/monitorperf/images/FTN/',
        'report_dir':'/opt/monitorperf/reports/FTN'
    }
},
'global':{

}  
}